travis:
  secure:
    BINSTAR_TOKEN: F4Q1UVqalqo102zbBxRNwPfP355YqXa1E/3k6OJFomRJQNnjmZXVUoy/6Fj6zxq/bXRRK5QQAN1AeeWAStQx0sxEPYp6iuDNOZVwVuSBdx8WATPNc5QDz0NC783eO6vuTqe1FQ2A4R7f/RhZEq3zGGIOP7OXF3gKzr076TNobc9i4HD63eMCbTHs+8f7Sf8oucKHFIhvL55l/Nwyhh97zshs3AWRmcBBl8yLpjHLnT2PRo3tumSFwKWThjvB52eTEgc84x0mPFoENZtd0AA4KZxShbUTQkek/Z3pRmrBmUOW30D/NklDU9wLNr2XTlbkYGq9pdD6qUIbY/ce3xGUMkNKC4enTh8oRVrWf25s1d2Q6qhgUC+oKlTYjVllMgoScjOX8hFaVQV0CYI0XPsMRvOgUOWn72vrelr6ooDVcXCMy/evWRunIsvYR+kvyVghKIkktAgkZX0sbsT5c9uGllnKhMPbERct6TS6TLw9U+7I2jlP9wE93A6vPlPU7XBTbHvzakG7/Kq/kgN+8QK/VADhgXO+gYxXX5pVG7d61iiIcKdJ32eAkDqmPB4Jm5Q6DrcdgrQtPpdI5DKuxmiQpdvI8FAfwLhoGpK8Sn5Gp4t/nPGdO5lpJU/Y0vpV68s3tIYwWz2YiPtbaaeVbDY2SwnAoLhmeiksner6D+WPO98=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
