travis:
  secure:
    BINSTAR_TOKEN: OcM2qyQBNamdDgcwpLEIs/Y3yCJt0cF7X3mmuw3C9rFZYXLm+mYXD/FHbgqxsBiCe04pPHV2PqiHZSb3ABjitGyw2qmgXpvQnjMNd9Y9cen0jbGnhQ+0X+IavvdlNTPa0bXq0ro1n8u04UPVE5O1faH7csl6Vr9rWAapklAG2i7ql7d7nP+E2YFGYrpPJ10B+xU4MbwpL3Hmtu1v+/nbIExw4UdgzRzLXVjzOGpfksDce8lIUXRGOqmJVSM6ng6d1nV8Vs09ovJzYZmD7m62Dbt8AwdJ1a/8kQtstXkmx5ypQPQoQfA13H3/J/YUJudcoldbjn3lB7QncO1TwNsYmJ/WGRkiwLA7sJniExAItvsG8tOHtf3kyAiJWwSQi0qYDoNSzuc2JiL4DxvJrSj8It6wp1vYxhhhkoKxeJmwfhL2aAj4FcNFlxYNw9jm2TkA8OrgUNM6QJa52WMNi5KEsvQnKc9S/GBQQrWWDEqug6RvETfBLauEscqyl8c5H/FMy5kMaTN4InFcde1hgj/xQKk/6ZP2annUq5KBdXd5DcP0wMFGnUEoTn/DM3lp+VWNOWyvdmsw7nuEOCOOJf1KEBYSSvuujlascgjGMXRjXlmBCiDv6GFSUotbB73oltWOeQCRjl0SBx0vYt46a+rUWI86vaIjqOFKFVKUXrUzClg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
