travis:
  secure:
    BINSTAR_TOKEN: TFft97HLvy1+YXe+Ze+czUKKPBpkngf+hPkHS/u+olLFI1TAYajVZ396hkBfUEhaR8MIYRpg8AefSs6qXh9I0in3SBG6NhZaSOEKHwSoqPyz7Udtt9/wMBZOOL/zYHi6Mmtc/M8EWwLJT8zW3Icd7tAJ7mFwfLAHOFaF6Zzti9Bdr59UVexXoqwe+jQQ9Hg9eUc8HX5S1TuY3/X6K0ykRelSDXNySbOstPt8E/mW8QBW4MLmMcupVYprTg0wfKA9hsxSg3Vzc0vIGVM1H2JABoXPpn0Paaa2wsov0jaQpNC4CIJBQqWNMHoJxduFg3qBNrz6ikVRt0ufj89X7Pq9QY0oAIQ03UdgNu0Nk40DKAeCu9KM6evTgDhlmg/vCvLWz7eb3DKTS0ZlFatoplGHE6HWmxNOiXsvVIu17BJhWCQaRFYZX8rCcF56Mzkq62Fh2IXUgiT6+rxvtaoxnf67jbMdaGpsLZGmtY9SpmK8qlfKhRpbySA3zxM5GBNMLPSpheQU65T+w2jUEeHg+vSK6fymEELsB9qRm+xx/gAW09bUkTtSiTqWLEXm+OPAtOV4K13c5OJa3VbpWEzbX62cjEoLIA9XUZ+jZjSq7aqoiLXlQcXMeKNfjUi2zFceTSrHlTQ7YAS1gTT0B8exuzx8HlO0Xjwh5Tus9p5t2aieots=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
